//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UET_CSE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddAcademic
    {
        public string Degree_Program { get; set; }
        public int Id { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public string Duration { get; set; }
    }
}
