//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UET_CSE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddAchievement
    {
        public string Name { get; set; }
        public System.DateTime Achievement_Date { get; set; }
        public string Achievement { get; set; }
        public string Email { get; set; }
        public string Image_Path { get; set; }
        public int Id { get; set; }
    }
}
