//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UET_CSE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddDateSheet
    {
        public string Session { get; set; }
        public string Section { get; set; }
        public string Day { get; set; }
        public System.DateTime Date { get; set; }
        public string Program { get; set; }
        public string Subject { get; set; }
        public string Supritendent_Name { get; set; }
        public string Time { get; set; }
        public string Hall { get; set; }
        public int Id { get; set; }
    }
}
