//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UET_CSE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class AddEvent
    {
        public int Id { get; set; }
        [Display(Name = "Event Name ")]

        public string Event_Name { get; set; }
        public string Description { get; set; }
        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        public DateTime Start_Date { get; set; }
        [Display(Name = "End Date ")]
        [DataType(DataType.Date)]
        public DateTime End_Date { get; set; }
        [Display(Name = "Ticket Price ")]

        public string Ticket_Price { get; set; }
        public string Place { get; set; }
        public string ImagePath { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
