//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UET_CSE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class AddFaculty
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        public string ImagePath { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        [Required]
        public string Deisgnation { get; set; }
        [Required]
        public string Qualification { get; set; }
        [Required]
        [Display(Name = "Other Qualification")]
        public string Other_Qualification { get; set; }
        [Required]
        public string Gender { get; set; }

    }
}
