//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UET_CSE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddTimeTable
    {
        public int Id { get; set; }
        public string SubjectName { get; set; }
        public string SubjectAbbreviation { get; set; }
        public string Day { get; set; }
        public string Place { get; set; }
        public string Session { get; set; }
        public string Section { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string TeacherName { get; set; }
    }
}
