//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UET_CSE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public string SubjectCode { get; set; }
        public string SubjectName { get; set; }
        public string SubjectAbbreviation { get; set; }
        public int CreditHours { get; set; }
        public string SemesterNumber { get; set; }
    }
}
