//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UET_CSE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registered_Student
    {
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public string CNIC { get; set; }
        public string Registration_Number { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Session { get; set; }
        public string Section { get; set; }
        public string Type { get; set; }
        public int Id { get; set; }
    }
}
